spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    hikari:
      maximum-pool-size: 5 # 커넥션 수 10 -> 5
      minimum-idle: 2

  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: ${BACKEND_URL}/login/oauth2/code/naver
          google:
            redirect-uri: ${BACKEND_URL}/login/oauth2/code/google
          kakao:
            redirect-uri: ${BACKEND_URL}/login/oauth2/code/kakao

app:
  oauth2:
    redirect-uri: ${FRONTEND_URL}/oauth2/callback
    failure-redirect-uri: ${FRONTEND_URL}/oauth2/error
  cors:
    allowed-origins: ${FRONTEND_URL}
  cookie:
    secure: true
    same-site: None

logging:
  level:
    org.springframework.security: INFO